---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "repeatmasker_rmouttogff3"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "bioconda::repeatmasker=4.1.5"
